# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luzfcb_djdocuments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoTemplate',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='esta_ativo',
            field=models.NullBooleanField(default=True, editable=False),
        ),
    ]
