# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luzfcb_djdocuments', '0002_auto_20160511_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='documento',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='luzfcb_djdocuments.Documento'),
        ),
    ]
