# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:19
from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luzfcb_djdocuments', '0002_auto_20160307_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTemplate',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('luzfcb_djdocuments.documento',),
        ),
    ]
