# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luzfcb_djdocuments', '0003_auto_20160512_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='esta_ativo',
            field=models.NullBooleanField(default=True),
        ),
    ]
