# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luzfcb_djdocuments', '0005_auto_20160512_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
