# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luzfcb_djdocuments', '0006_auto_20160512_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='assunto',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='assunto',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
