# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djdocuments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='data_finalizado',
            new_name='data_assinado',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='finalizado',
            new_name='esta_pronto_para_assinar',
        ),
        migrations.RenameField(
            model_name='historicaldocumento',
            old_name='data_finalizado',
            new_name='data_assinado',
        ),
        migrations.RenameField(
            model_name='historicaldocumento',
            old_name='finalizado',
            new_name='esta_pronto_para_assinar',
        ),
    ]
