# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djdocuments', '0002_auto_20160706_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='esta_assinado',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='esta_ativo',
            field=models.NullBooleanField(default=True, editable=False),
        ),
    ]
