# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djdocuments', '0003_auto_20160707_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='uuid_hash',
            new_name='pk_uuid',
        ),
        migrations.RenameField(
            model_name='historicaldocumento',
            old_name='uuid_hash',
            new_name='pk_uuid',
        ),
    ]
